services:
  instagrapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ${PWD}/api/.env
    ports:
      - "${INSTAGRAPI_PORT}:8000"
  discord-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - ${PWD}/bot/.env
