services:
  instagrapi:
    container_name: instagrapi
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ${PWD}/api/.env
    ports:
      - "${INSTAGRAPI_PORT}:8000"
  discord-bot:
    depends_on:
      - instagrapi
    container_name: instagram-notifier
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - ${PWD}/bot/.env
